In [1]:
import tensorflow as tf

2025-09-04 23:46:30.225358: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-04 23:46:30.583369: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-04 23:46:32.200917: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [2]:
# 1. Scalar (0d tensor)
scalar = tf.constant(8)
print(f"Scalar: {scalar} and shape:{scalar.shape}")

Scalar: 8 and shape:()


2025-09-04 23:48:09.801245: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [3]:
scalar = tf.constant(5)
print("Scalar:", scalar)
print("Shape:", scalar.shape)

Scalar: tf.Tensor(5, shape=(), dtype=int32)
Shape: ()


In [4]:
# 2. vector (1d tensor)
vector = tf.constant([23,4,5,6,7])
print(f'vector is {vector} and shape: {vector.shape}')

vector is [23  4  5  6  7] and shape: (5,)


In [5]:
# 3. matrix (2D tensor)
matrix = tf.constant([[1,2],[3,4]])
print(f"matrix {matrix} and shape : {matrix.shape}")

matrix [[1 2]
 [3 4]] and shape : (2, 2)


In [6]:
# 4. 3d tensor
tensor3d = tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]])
print(f'tensor3d :{tensor3d} and shape: {tensor3d.shape}')

tensor3d :[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]] and shape: (2, 2, 2)


In [7]:
# 4. 3D Tensor
tensor3d = tf.constant([[[1], [2]], [[3], [4]]])
print("\n3D Tensor:\n", tensor3d)
print("Shape:", tensor3d.shape)


3D Tensor:
 tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
Shape: (2, 2, 1)


In [8]:
# 5. tensor4d
tensor4d = tf.constant([[[[1,2],[2,3]]]])
print(f'tensor4d {tensor4d} and shape {tensor4d.shape}')

tensor4d [[[[1 2]
   [2 3]]]] and shape (1, 1, 2, 2)


In [14]:
tensor4d = tf.constant([[[[1],[2],[3],[4]],[[1],[2],[3],[4]],[[1],[2],[3],[4]]],[[[1],[2],[3],[4]],[[1],[2],[3],[4]],[[1],[2],[3],[4]]]])
print(f'tensor4d {tensor4d} and shape{tensor4d.shape}')

tensor4d [[[[1]
   [2]
   [3]
   [4]]

  [[1]
   [2]
   [3]
   [4]]

  [[1]
   [2]
   [3]
   [4]]]


 [[[1]
   [2]
   [3]
   [4]]

  [[1]
   [2]
   [3]
   [4]]

  [[1]
   [2]
   [3]
   [4]]]] and shape(2, 3, 4, 1)


In [15]:
import tensorflow as tf
from tensorflow.keras import layers, models

# MNIST dataset লোড করা
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Normalize করা
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [16]:
inputs = tf.keras.Input(shape=(28, 28))  # input layer

x = layers.Flatten()(inputs)             # 28x28 => 784
x = layers.Dense(128, activation='relu')(x)
x = layers.Dropout(0.3)(x)
x = layers.Dense(64, activation='relu')(x)

outputs = layers.Dense(10, activation='softmax')(x)  # 10 ক্লাস

model = tf.keras.Model(inputs=inputs, outputs=outputs)


In [17]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5, batch_size=32)


Epoch 1/5


2025-09-05 00:11:08.517795: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9058 - loss: 0.3092
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9524 - loss: 0.1557
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9615 - loss: 0.1241
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9658 - loss: 0.1093
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9704 - loss: 0.0956


In [18]:
model.evaluate(x_test, y_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 741us/step - accuracy: 0.9725 - loss: 0.0847


[0.08471190929412842, 0.9725000262260437]

In [19]:
inputs = tf.keras.Input(shape=(28, 28))  # input layer

x = layers.Flatten()(inputs)             # 28x28 => 784
x = layers.Dense(128, activation='relu')(x)
x = layers.Dense(64,activation='relu')(x)
x = layers.Dropout(0.3)(x)
x = layers.Dense(64, activation='relu')(x)

outputs = layers.Dense(10, activation='softmax')(x)  # 10 ক্লাস

model = tf.keras.Model(inputs=inputs, outputs=outputs)


In [20]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10, batch_size=32)


Epoch 1/10


2025-09-05 00:13:49.258048: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9050 - loss: 0.3150
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9584 - loss: 0.1393
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9700 - loss: 0.1023
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9755 - loss: 0.0802
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9790 - loss: 0.0686
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9810 - loss: 0.0596
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9838 - loss: 0.0515
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9850 - loss: 0.0479
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9868 - loss: 0.0411
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9878 - loss: 0.0385


In [21]:
model.evaluate(x_test, y_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.9775 - loss: 0.0835


[0.08352723717689514, 0.9775000214576721]

In [22]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Load MNIST
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Reshape for CNN: (samples, height, width, channels)
x_train = x_train.reshape(-1, 28, 28, 1) / 255.0
x_test = x_test.reshape(-1, 28, 28, 1) / 255.0


In [23]:
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(10, activation='softmax')
])


/home/atiar/venv-folder/tf_env/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [24]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)

history = model.fit(x_train, y_train, epochs=15,
                    validation_split=0.2,
                    callbacks=[early_stop])



Epoch 1/15


2025-09-05 00:49:55.273001: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 150528000 exceeds 10% of free system memory.


1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.9234 - loss: 0.2479 - val_accuracy: 0.9824 - val_loss: 0.0622
Epoch 2/15
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9741 - loss: 0.0880 - val_accuracy: 0.9862 - val_loss: 0.0521
Epoch 3/15
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9803 - loss: 0.0652 - val_accuracy: 0.9868 - val_loss: 0.0477
Epoch 4/15
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9835 - loss: 0.0538 - val_accuracy: 0.9873 - val_loss: 0.0489
Epoch 5/15
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9857 - loss: 0.0459 - val_accuracy: 0.9895 - val_loss: 0.0416
Epoch 6/15
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9876 - loss: 0.0394 - val_accuracy: 0.9902 - val_loss: 0.0384
Epoch 7/15
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9905 - loss: 0.0304 - val_accuracy: 0.9889 - val_loss: 0.0475
Epoch 8/15
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9911 - loss: 0.0275 - val_accura

In [25]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 11, 11, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 5, 5, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 1600)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │       102,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 365,792 (1.40 MB)

 Trainable params: 121,930 (476.29 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 243,862 (952.59 KB)

In [26]:
model.evaluate(x_test, y_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9926 - loss: 0.0281


[0.028125524520874023, 0.9926000237464905]

In [32]:
# 1. Create the datagen with validation split
datagen = ImageDataGenerator(
    rotation_range=10,
    zoom_range=0.1,
    width_shift_range=0.1,
    height_shift_range=0.1,
    validation_split=0.2  # ✅ এখানে split
)

# 2. তৈরি করো train ও validation generator আলাদা করে
train_generator = datagen.flow(x_train, y_train, batch_size=64, subset='training')
val_generator = datagen.flow(x_train, y_train, batch_size=64, subset='validation')

# 3. model.fit এ এখন validation_data ব্যবহার করো
history_aug = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=15,
)


Epoch 1/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.9798 - loss: 0.0674 - val_accuracy: 0.9857 - val_loss: 0.0487
Epoch 2/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.9808 - loss: 0.0620 - val_accuracy: 0.9851 - val_loss: 0.0489
Epoch 3/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.9826 - loss: 0.0608 - val_accuracy: 0.9875 - val_loss: 0.0397
Epoch 4/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.9830 - loss: 0.0556 - val_accuracy: 0.9891 - val_loss: 0.0381
Epoch 5/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.9827 - loss: 0.0572 - val_accuracy: 0.9874 - val_loss: 0.0409
Epoch 6/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.9836 - loss: 0.0534 - val_accuracy: 0.9858 - val_loss: 0.0479
Epoch 7/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - accuracy: 0.9846 - loss: 0.0508 - val_accuracy: 0.9872 - val_loss: 0.0401
Epoch 8/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - accuracy: 0.9849 - loss: 0.0506 - 

In [33]:
# 1. Create the datagen with validation split
datagen = ImageDataGenerator(
    rotation_range=10,
    zoom_range=0.1,
    width_shift_range=0.1,
    height_shift_range=0.1,
    validation_split=0.2  # ✅ এখানে split
)

# 2. তৈরি করো train ও validation generator আলাদা করে
train_generator = datagen.flow(x_train, y_train, batch_size=64, subset='training')
val_generator = datagen.flow(x_train, y_train, batch_size=64, subset='validation')

# 3. model.fit এ এখন validation_data ব্যবহার করো
history_aug = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=15,
    callbacks=[early_stop]
)


Epoch 1/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - accuracy: 0.9867 - loss: 0.0440 - val_accuracy: 0.9900 - val_loss: 0.0353
Epoch 2/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - accuracy: 0.9884 - loss: 0.0397 - val_accuracy: 0.9884 - val_loss: 0.0386
Epoch 3/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 18ms/step - accuracy: 0.9878 - loss: 0.0429 - val_accuracy: 0.9883 - val_loss: 0.0395
Epoch 4/15
750/750 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.9881 - loss: 0.0413 - val_accuracy: 0.9897 - val_loss: 0.0389
