In [2]:
import torch

# create tensor
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([6,7,8,9,10])

# operation
print(x+y)
print(x*y)
# GPU তে পাঠানো (যদি CUDA সাপোর্ট করে)
if torch.cuda.is_available():
    x = x.to("cuda")
    print(x)

tensor([ 7,  9, 11, 13, 15])
tensor([ 6, 14, 24, 36, 50])


# AutoGrad(Autometic Differentiation)


In [5]:
# requires grad enabled tensor
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0,requires_grad=True)

# function
y = a**2 +b**3

y.backward()
print(a.grad)  # dy/da = 2a = 4
print(b.grad)  # dy/db = 3b^2 = 27

tensor(4.)
tensor(27.)


nn.Module (Model বানানো)

In [6]:
import torch.nn as nn

# Simple linear regression model
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)  # y = wx + b

    def forward(self, x):
        return self.linear(x)

model = LinearModel()
print(model)


LinearModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


Training Pipeline (Data → Model → Loss → Optimizer → Update)

In [7]:
import torch.optim as optim

# Data
x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[2.0], [4.0], [6.0]])

# Model
model = nn.Linear(1, 1)

# Loss + Optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    # Forward
    y_pred = model(x)
    loss = criterion(y_pred, y)

    # Backward
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("Prediction for 4.0:", model(torch.tensor([[4.0]])))


Prediction for 4.0: tensor([[7.7170]], grad_fn=<AddmmBackward0>)


In [16]:
import torch, torch.nn as nn, torch.optim as optim

x = torch.tensor([[1.0],[2.0],[3.0]])
y = torch.tensor([[2.0],[4.0],[6.0]])
model = nn.Linear(1,1)
opt = optim.SGD(model.parameters(), lr=0.01)
loss_fn = nn.MSELoss()

for epoch in range(200):
    pred = model(x)
    loss = loss_fn(pred, y)
    opt.zero_grad(); loss.backward(); opt.step()
print(model(torch.tensor([[4.0]])))


tensor([[7.3015]], grad_fn=<AddmmBackward0>)
