# torch

### torch.is_tensor
torch.is_tensor(obj, /)
[source]

Returns True if obj is a PyTorch tensor.

Note that this function is simply doing isinstance(obj, Tensor). Using that isinstance check is better for typechecking with mypy, and more explicit - so it’s recommended to use that instead of is_tensor.

Parameters

    obj (object) – Object to test
Return type

    typing_extensions.TypeIs[Tensor]


In [4]:
import torch
x=torch.tensor([2,3,4])
print(x)
torch.is_tensor(x)

tensor([2, 3, 4])


True

In [11]:
import numpy as np
import pandas as pd
x=np.arange(3)
y=np.arange(3)
df = pd.DataFrame([x,y])
print(df)
tensor_df = torch.tensor(df.values) # .values gives the underlying numpy array
print(tensor_df)

   0  1  2
0  0  1  2
1  0  1  2
tensor([[0, 1, 2],
        [0, 1, 2]])


### torch.is_floating_point
torch.is_floating_point(input)

    Returns True if the data type of input is a floating point data type i.e., one of torch.float64, torch.float32, torch.float16, and torch.bfloat16.

    Parameters

        input (Tensor) – the input tensor.



In [21]:
x = torch.tensor(3.3)
print(x)
print(torch.is_floating_point(x))

tensor(3.3000)
True


### torch_is_nonzero
torch.is_nonzero(input)

Returns True if the input is a single element tensor which is not equal to zero after type conversions. i.e. not equal to torch.tensor([0.]) or torch.tensor([0]) or torch.tensor([False]). Throws a RuntimeError if torch.numel() != 1 (even in case of sparse tensors).

Parameters

    input (Tensor) – the input tensor.


In [18]:
torch.is_nonzero(torch.tensor([2]))

True

In [19]:
torch.is_nonzero(torch.tensor([3]))

True

In [22]:
torch.is_nonzero(torch.tensor([1.5]))

True

In [23]:
torch.is_nonzero(torch.tensor([False]))

False

In [24]:
torch.is_nonzero(torch.tensor([1,2,3,4]))

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [29]:
torch.is_nonzero(torch.tensor([]))

RuntimeError: Boolean value of Tensor with no values is ambiguous

### torch.set_default_dtype
torch.set_default_dtype(d, /)
[source]

Sets the default floating point dtype to d. Supports floating point dtype as inputs. Other dtypes will cause torch to raise an exception.

When PyTorch is initialized its default floating point dtype is torch.float32, and the intent of set_default_dtype(torch.float64) is to facilitate NumPy-like type inference. The default floating point dtype is used to:

    Implicitly determine the default complex dtype. When the default floating type is float16, the default complex dtype is complex32. For float32, the default complex dtype is complex64. For float64, it is complex128. For bfloat16, an exception will be raised because there is no corresponding complex type for bfloat16.

    Infer the dtype for tensors constructed using Python floats or complex Python numbers. See examples below.

    Determine the result of type promotion between bool and integer tensors and Python floats and complex Python numbers.

Parameters

    d (torch.dtype) – the floating point dtype to make the default.


In [30]:
# initial default for floating point is torch.float32
# python floats are interpreted as float32
torch.tensor([2,4,5,6.2]).dtype

torch.float32

In [31]:
# initial default for floating point is torch.complex64
# complex python numbers are interpreted as complex64
torch.tensor([2,4,5,6j]).dtype

torch.complex64

In [32]:
torch.set_default_dtype(torch.float64)

In [33]:
# python floats are now interpreted as float64
torch.tensor([1.2,3]).dtype

torch.float64

### torch.get_default_dtype
torch.get_default_dtype() → torch.dtype

Get the current default floating point torch.dtype.

In [34]:
torch.get_default_dtype()

torch.float64

### torch.get_default_device


In [35]:
torch.get_default_device()

device(type='cpu')

In [36]:
torch.get_default_device()

device(type='cpu')

### torch.set_default_tensor_type

torch.set_default_tensor_type(t, /)

Sets the default torch.Tensor type to floating point tensor type t. This type will also be used as default floating point type for type inference in torch.tensor().

The default floating point tensor type is initially torch.FloatTensor.

Parameters

    t (type or string) – the floating point tensor type or its name


In [37]:
torch.tensor([1,2,3,4]).dtype

torch.int64

In [39]:
torch.tensor([1.2,3,4]).dtype

torch.float64

### torch.numel
torch.numel(input: Tensor) → int

Returns the total number of elements in the input tensor.

Parameters

    input (Tensor) – the input tensor.


In [40]:
a = torch.randn(1,2,3,4,5)
torch.numel(a)

120

In [41]:
a = torch.zeros(4,4)
torch.numel(a)

16

### torch.set_printoptions
torch.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, profile=None, sci_mode=None)
[source]

Set options for printing. Items shamelessly taken from NumPy

`parameters: `


        precision – Number of digits of precision for floating point output (default = 4).

        threshold – Total number of array elements which trigger summarization rather than full repr (default = 1000).

        edgeitems – Number of array items in summary at beginning and end of each dimension (default = 3).

        linewidth – The number of characters per line for the purpose of inserting line breaks (default = 80). Thresholded matrices will ignore this parameter.

        profile – Sane defaults for pretty printing. Can override with any of the above options. (any one of default, short, full)

        sci_mode – Enable (True) or disable (False) scientific notation. If None (default) is specified, the value is defined by torch._tensor_str._Formatter. This value is automatically chosen by the framework.



In [43]:
# limit the precision of elements
torch.set_printoptions(precision=2)

In [44]:
torch.tensor([1.123456])

tensor([1.12])

In [62]:
# limit the number of elements shown
torch.set_printoptions(threshold=10)

In [63]:
torch.arange(20)

tensor([ 0,  1,  2,  ..., 17, 18, 19])

In [64]:
torch.set_printoptions(profile='default')


Excellent observation.

When PyTorch summarizes large tensors using `...`, it **by default shows the first 3 and last 3 elements** of **1D tensors**.

---

### 🔍 Why does it show first 3 and last 3?

This behavior is **hardcoded** into PyTorch's print formatting logic for 1D tensors when summarization (`...`) is triggered due to exceeding the `threshold`.

#### ✔ PyTorch default summary logic:

For **1D tensors**, when the number of elements exceeds the `threshold`, PyTorch shows:

* The **first 3 elements**
* An ellipsis `...`
* The **last 3 elements**

---

### 📘 Example:

```python
import torch

torch.set_printoptions(threshold=2)

a = torch.arange(10)
print(a)
```

#### Output:

```
tensor([0, 1, 2, ..., 7, 8, 9])
```

It shows 3 head elements: `[0, 1, 2]`
And 3 tail elements: `[7, 8, 9]`

---

### 🛠 Can this be changed?

Unfortunately, **PyTorch does not expose settings** to customize the number of head/tail elements shown in the abbreviated display. The behavior is **not user-configurable** via `set_printoptions`.

However, you can implement a **custom print function** if needed:

```python
def custom_tensor_preview(tensor, head=3, tail=3):
    total = tensor.numel()
    if total <= head + tail:
        return tensor
    else:
        head_vals = tensor[:head]
        tail_vals = tensor[-tail:]
        return f"tensor([{', '.join(map(str, head_vals.tolist()))}, ..., {', '.join(map(str, tail_vals.tolist()))}])"

a = torch.arange(100)
print(custom_tensor_preview(a))
```

#### Output:

```
tensor([0, 1, 2, ..., 97, 98, 99])
```

---

### ✅ Summary:

| Behavior      | Value                            |
| ------------- | -------------------------------- |
| Always shows  | First 3, Last 3 (for 1D tensors) |
| Triggered by  | `tensor.numel() > threshold`     |
| Customizable? | ❌ Not via `set_printoptions`     |
| Workaround    | ✅ Use a custom print function    |

Let me know if you'd like a version that works for multi-dimensional tensors too.


In [66]:
torch.set_printoptions(profile='default')

In [67]:
torch.tensor(1.23456)

tensor(1.2346)

In [68]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### torch.tensor
torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor

Constructs a tensor with no autograd history (also known as a “leaf tensor”, see Autograd mechanics) by copying data.

- torch.as_tensor() preserves autograd history and avoids copies where possible. torch.
- from_numpy() creates a tensor that shares storage with a NumPy array.

Keyword Arguments

- dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from data.

- device (torch.device, optional) – the device of the constructed tensor. If None and data is a tensor then the device of data is used. If None and data is not a tensor then the result tensor is constructed on the current device.

- requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

- pin_memory (bool, optional) – If set, returned tensor would be allocated in the pinned memory. Works only for CPU tensors. Default: False.





In [69]:
torch.tensor([])

tensor([])

In [70]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [71]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])