# constants

In [1]:
import numpy as np
np.e

2.718281828459045

In [2]:
np.pi

3.141592653589793

In [3]:
np.euler_gamma

0.5772156649015329

In [4]:
np.inf

inf

In [5]:
1/2

0.5

In [7]:
np.array([2])/0

/tmp/ipykernel_51679/1608682846.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([2])/0


array([inf])

# array creation

In [8]:
np.empty((2,3))

array([[1.34341557e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.85154273e-310, 6.85154273e-310]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])