### Array creation

In [1]:
import numpy as np

# basic array
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],[1,2,3]])

In [2]:
a

array([1, 2, 3, 4, 5])

In [3]:
b

array([[1, 2, 3],
       [1, 2, 3]])

# array initializers

    - np.zeros((2,3)) #2x3 array of zeros
    - np.ones((2,3)) #2x3 arrays of ones
    - np.full((2,3),7) #2x3 array filled 7
    - np.eye(3) #identity matrix
    - np.arange(0,10,2) #[0,2,4,6,8]
    - np.linspace(0,1,5) # [0,0.25,0.5,0.75,1]
    - np.random.rand(2,3) #random floats(0-1)
    - np.random.randin(0,10,(3,3)) #Random ints

array operations
1. a.shape
2. a.reshape(3,5) #(row,col)
3. a.flatten()
4. a.T  #transpose

indexing and slicing
-  a[0:1] #[start,end]
-  a[0:4:2] #[start,end,step]
- negative value last to first


# Mathiematical operations
- a+b
- a-b
- a*b
- a/b
- a//b
- a%b
- np.dot(a,b) # a and b are multiply
- np.sqrt(a) # root of a
- np.exp(a) # e^a[0] this only 0 indec and others elements are same
- np.sum(a, axis=0) #array all elements sumation here 
### More Intuition:
    - axis=0 → sum down columns
    - axis=1 → sum across rows
- np.mean(a) #find the mean value of an array
- np.std(a) #find standarddeviation of array
- np.max(a) #find the max value of a array
- np.min(a) #find the min value of a array

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.exp(a)
b

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
np.sum(a, axis=0)

np.int64(45)

In [11]:
a = np.array([[1,3,4],[2,3,4]])
np.sum(a,axis=1)

array([8, 9])

In [12]:
np.std(a)

np.float64(1.0671873729054748)

In [ ]:
### Advanced Indexing & Boolean Masking
- boolean indexing
- fancy indexing
- where function

In [17]:
a = np.arange(10)

In [18]:
a[a>5]

array([6, 7, 8, 9])

In [20]:
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])


In [21]:
a[[0,2],[3,4]]

array([ 3, 14])

### is a fancy indexing operation that selects:

- From row 0, column 3 → a[0, 3] → 3
- From row 2, column 4 → a[2, 4] → 14
- '''
- 🧠 Rule:
- If a is 2D, then:
   - a[[i1, i2], [j1, j2]] → [a[i1, j1], a[i2, j2]]
- It picks (i1, j1) and (i2, j2) — not all combinations!
'''


In [22]:
np.where(a>5,1,0)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

The expression:

```python
np.where(a > 5, 1, 0)
```

is a **vectorized conditional operation** in NumPy.

---

### ✅ What it means:

* `a > 5`: creates a Boolean array (True where elements > 5).
* `np.where(condition, x, y)` returns:

  * `x` where `condition` is True
  * `y` where `condition` is False

So this line creates a **new array of the same shape** as `a`, where:

* elements > 5 become `1`
* elements ≤ 5 become `0`

---

### 🔍 Example:

```python
import numpy as np

a = np.array([[2, 6, 3],
              [7, 1, 8]])

result = np.where(a > 5, 1, 0)
```

#### Output:

```python
array([[0, 1, 0],
       [1, 0, 1]])
```

---

### 🧠 Summary:

* `np.where(condition, true_value, false_value)` is a fast way to apply if-else logic to arrays.
* Keeps the **shape** of `a`.

Let me know if you want to replace with actual values instead of 1 and 0.


In [26]:

a = np.array([2, 3, 4, 6, 7])
result = np.where(a % 2 == 0, 1, 0)
print(result)

# where even number is 1 and odd number is 0

[1 0 1 1 0]


# BroadCasting


In [ ]:
broadcasting = automic expansion of smaller arrays


In [28]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])
a+b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

Great question! Let's break it down:

```python
a = np.array([1, 2, 3])         # Shape: (3,) → 1D row vector
b = np.array([[1], [2], [3]])   # Shape: (3, 1) → 2D column vector
a + b
```

---

### 🔍 Shapes:

* `a.shape` → `(3,)`
* `b.shape` → `(3, 1)`

When you do `a + b`, **NumPy uses broadcasting**.

---

### ✅ Broadcasting behavior:

* `a` (1D row) becomes a **(1, 3)** row vector
* `b` (column) is **(3, 1)**
  → NumPy broadcasts them to a **(3, 3)** result.

---

### Computation:

You’re basically doing:

```
[[1],      +   [1, 2, 3]  →  [1+1, 1+2, 1+3] → [2, 3, 4]
 [2],                         [2+1, 2+2, 2+3] → [3, 4, 5]
 [3]]                         [3+1, 3+2, 3+3] → [4, 5, 6]
```

---

### ✅ Final Output:

```python
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])
```

---

### 🧠 Summary:

* NumPy uses **broadcasting** to align shapes
* Adds each element in `a` to each row of `b`
* Result shape: **(3, 3)**

Let me know if you want to visualize this as a grid or matrix!


## useful Numpy functions
- np.unique()  # unique element
- np.sort() #sorts array
- np.argsort() #Returns sorted indices
- np.argmin() #Index of minimum value
- np.argmax() #Index of Maximum value
- np.cumsum() #cumulative sum
- np.cumprod() #cumulitive product
- np.clip(a, min,max) #limit values


Great list! You're on the right track 👏
Let me correct a small typo and enhance it with examples for clarity.

---

### ✅ Useful NumPy Functions:

```python
import numpy as np
```

#### 🔹 `np.unique(a)`

> Returns the **sorted unique elements** of an array.

```python
np.unique([1, 2, 2, 3])  # ➝ array([1, 2, 3])
```

---

#### 🔹 `np.sort(a)`

> Sorts the array (along specified axis if multi-dimensional).

```python
np.sort([3, 1, 2])  # ➝ array([1, 2, 3])
```

---

#### 🔹 `np.argsort(a)`

> Returns the **indices** that would sort the array.

```python
np.argsort([3, 1, 2])  # ➝ array([1, 2, 0])
```

---

#### 🔹 `np.argmin(a)`

> Returns the **index** of the **minimum** value.

```python
np.argmin([5, 2, 8])  # ➝ 1
```

---

#### 🔹 `np.argmax(a)`

> Returns the **index** of the **maximum** value.

```python
np.argmax([5, 2, 8])  # ➝ 2
```

---

#### 🔹 `np.cumsum(a)`

> Returns the **cumulative sum** of elements.

```python
np.cumsum([1, 2, 3])  # ➝ array([1, 3, 6])
```

---

#### 🔹 `np.cumprod(a)` ✅ (**Corrected spelling**)

> Returns the **cumulative product** of elements.

```python
np.cumprod([1, 2, 3])  # ➝ array([1, 2, 6])
```

---

#### 🔹 `np.clip(a, min, max)`

> Limit values in an array:
>
> * Less than `min` ➝ set to `min`
> * Greater than `max` ➝ set to `max`

```python
np.clip([1, 5, 9], 2, 6)  # ➝ array([2, 5, 6])
```



Let me know if you want more functions like `np.mean`, `np.std`, `np.linspace`, or matrix operations!


## Linear algebra with numpy array

- np.linalg.inv(a) #inverse
- np.linalg.det(a) #determinant
- np.linalg.eig(a) #Eigenvalues/vectors
- np.linalg.solve(A,b) #solve Ax=b

Excellent! Here's a cleaned-up and fully explained version of your list on **Linear Algebra with NumPy**, with examples for clarity:

---

### ✅ Linear Algebra with NumPy Arrays

All of these functions are found under `np.linalg` (NumPy's **linear algebra module**).

```python
import numpy as np
```

---

### 🔹 `np.linalg.inv(a)`

> Computes the **inverse** of a square matrix.

```python
a = np.array([[1, 2], [3, 4]])
np.linalg.inv(a)
# ➝ array([[-2. ,  1. ],
#           [ 1.5, -0.5]])
```

---

### 🔹 `np.linalg.det(a)`

> Computes the **determinant** of a square matrix.

```python
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)  # ➝ -2.0
```

---

### 🔹 `np.linalg.eig(a)`

> Computes **eigenvalues** and **eigenvectors**.

```python
a = np.array([[1, 2], [2, 1]])
values, vectors = np.linalg.eig(a)
# values  ➝ array([3., -1.])
# vectors ➝ array([[ 0.707, -0.707],
#                  [ 0.707,  0.707]])
```

---

### 🔹 `np.linalg.solve(A, b)`

> Solves the **system of linear equations**:
> $Ax = b$

```python
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
np.linalg.solve(A, b)  # ➝ array([3., 2.])
```

---

### 🧠 Bonus Suggestions:

You might also find these useful:

* `np.dot(a, b)` — Dot product
* `np.matmul(a, b)` — Matrix multiplication
* `np.transpose(a)` — Transpose matrix
* `np.linalg.norm(a)` — Vector or matrix norm
* `np.trace(a)` — Trace (sum of diagonal elements)

---

Let me know if you want a matrix visualization or step-by-step solving of linear systems!


# Random and Statistics
- np.random.seed(42) #for reproductibility
- np.random.normal(0,1,1000) #normal distribution
- np.random.binomial(n=10,p=0.5,size = 1000)
- np.mean(a)
- np.median()
- np.percential(a,75)
- np.std(a)
- np.var(a)


You're almost spot-on! Here’s the **corrected and clarified** version of your **Random and Statistics** section using NumPy, including a few important fixes (like typo in `percential` → `percentile`) and examples:

---

### ✅ Random Numbers & Statistics with NumPy

```python
import numpy as np
```

---

### 🔹 `np.random.seed(42)`

> Sets the **random seed** for reproducibility (same random numbers every time you run).

```python
np.random.seed(42)
```

---

### 🔹 `np.random.normal(loc=0, scale=1, size=1000)`

> Draws 1000 samples from a **normal (Gaussian) distribution** with mean `0` and standard deviation `1`.

```python
samples = np.random.normal(0, 1, 1000)
```

---

### 🔹 `np.random.binomial(n=10, p=0.5, size=1000)`

> Draws 1000 samples from a **binomial distribution** with:

* `n = 10` trials
* `p = 0.5` probability of success

```python
binomial_samples = np.random.binomial(n=10, p=0.5, size=1000)
```

---

### 🔹 `np.mean(a)`

> Computes the **mean (average)** of array `a`.

```python
np.mean([1, 2, 3])  # ➝ 2.0
```

---

### 🔹 `np.median(a)`

> Computes the **median** value of array `a`.

```python
np.median([1, 2, 3, 4])  # ➝ 2.5
```

---

### 🔹 `np.percentile(a, 75)`

> Returns the **75th percentile** value in array `a`.

✅ **Corrected typo**: `percential` ❌ → `percentile` ✅

```python
np.percentile([1, 2, 3, 4, 5], 75)  # ➝ 4.0
```

---

### 🔹 `np.std(a)`

> Computes the **standard deviation** of array `a`.

```python
np.std([1, 2, 3])  # ➝ 0.816...
```

---

### 🔹 `np.var(a)`

> Computes the **variance** of array `a`.

```python
np.var([1, 2, 3])  # ➝ 0.666...
```

---

### 🧠 Optional Additions:

* `np.min(a)` → Minimum value
* `np.max(a)` → Maximum value
* `np.histogram(a)` → Histogram bins and counts
* `np.random.randint(low, high, size)` → Random integers

---

Let me know if you want a PDF summary of all these NumPy sections!
