In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(arr))

45


##### Array creation

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [5]:
arr = np.array([[[2,43],[45,3]],[[3,4],[5,6]]])
arr

array([[[ 2, 43],
        [45,  3]],

       [[ 3,  4],
        [ 5,  6]]])

In [6]:
arr = np.zeros(2)
arr

array([0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
np.full((1,2),4)

array([[4, 4]])

In [12]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(0,200,3)

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198])

In [15]:
np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [16]:
np.random.rand(3,4)

array([[0.33161649, 0.68094202, 0.20336778, 0.29103153],
       [0.24053651, 0.71338566, 0.58666415, 0.63507826],
       [0.73846687, 0.61450319, 0.4436104 , 0.98655199]])

In [17]:
np.random.randn(3,4)

array([[-0.23417166, -1.20811279,  0.93867933,  0.25978473],
       [-1.5410912 , -0.52842974,  0.99798774,  0.9308099 ],
       [-0.26398897, -0.37205839, -0.01519226,  0.50809134]])

In [18]:
np.random.randint(1,10,(3,4))

array([[9, 7, 7, 1],
       [3, 3, 5, 1],
       [5, 3, 6, 6]])

In [19]:
arr = np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr.shape

(2, 3)

In [21]:
arr.ndim

2

In [22]:
arr.size

6

In [23]:
arr.dtype

dtype('int64')

In [24]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
arr.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [27]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### mathematical operations

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a+b

array([5, 7, 9])

In [29]:
a*b

array([ 4, 10, 18])

In [30]:
a-b

array([-3, -3, -3])

In [31]:
a/b

array([0.25, 0.4 , 0.5 ])

In [32]:
a//b

array([0, 0, 0])

In [33]:
a**2

array([1, 4, 9])

In [34]:
b**2

array([16, 25, 36])

In [35]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [36]:
np.sqrt([1,2,3])

array([1.        , 1.41421356, 1.73205081])

In [37]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [38]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

#### aggregation function

In [39]:
a = np.array([10,20,30])

np.sum(a)

np.int64(60)

In [40]:
np.mean(a)

np.float64(20.0)