# matrix

In [3]:
import numpy as np

In [11]:
identity = np.eye(3,2)
identity

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [12]:
identity.shape

(3, 2)

In [15]:
dig = np.diag((4,4))
dig

array([[4, 0],
       [0, 4]])

In [25]:
x = np.diag((3,4,6))
x

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [23]:
sum1 = np.trace(dig)
sum1

np.int64(8)

In [26]:
tr = np.trace(x)
tr

np.int64(13)

In [28]:
up =  np.triu((3,4))
up

array([[3, 4],
       [0, 4]])

In [29]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
a.shape

(9,)

In [35]:
a = a.reshape(3,3)

In [36]:
a.shape

(3, 3)

In [43]:
a = a.flat
a

In [46]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
a.ctypes

In [55]:
a.__lt__(3)

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [57]:
a.__le__(3)

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [58]:
a.__gt__(4)

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [60]:
a.__ge__(4)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [61]:
b = np.arange(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
a.__eq__(5)

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False])

In [64]:
a.__ne__(5)

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [72]:
a.__abs__()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


# 🔍 What is ndarray.__abs__(self)?
In NumPy:

   1. ndarray is the main array type.
   2.  __abs__ is the magic method for the built-in abs() function.
   3. So abs(a) is equivalent to a.__abs__() when a is a NumPy array.

### ✅ Return Type:
Returns a new ndarray with the absolute values.

Works element-wise.



| Expression       | Effect          | Works On          |
| ---------------- | --------------- | ----------------- |
| `~a`             | Bitwise NOT     | Integers/Booleans |
| `a.__invert__()` | Same as `~a`    | Integers/Booleans |
| `~True → False`  | Inverts boolean | Booleans          |
| `~5 → -6`        | `-5 - 1 = -6`   | Integers          |


In [73]:
~a

array([ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13,
       -14, -15])

In [74]:
a.__invert__()

array([ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13,
       -14, -15])


## The expression ndarray.__neg__(self) in NumPy corresponds to unary negation—that is, applying the minus (-) operator to each element of an array
## 🔍 What Does ndarray.__neg__() Do?
It implements the behavior of -a for a NumPy array a.

Internally, -a is equivalent to a.__neg__().

It returns a new array with all values negated (multiplied by -1).

| Expression    | Meaning                    |
| ------------- | -------------------------- |
| `-a`          | Calls `a.__neg__()`        |
| `a.__neg__()` | Returns `-1 * a`           |
| Result Type   | Same shape, negated values |


In [78]:
import numpy as np

a = np.array([1, -2, 3])

# Using the - operator
print(-a)               # Output: [-1  2 -3]

# Using __neg__ directly
print(a.__neg__())      # Output: [-1  2 -3]

[-1  2 -3]
[-1  2 -3]


| Expression    | Meaning                 |
| ------------- | ----------------------- |
| `+a`          | Calls `a.__pos__()`     |
| `a.__pos__()` | Returns array unchanged |
| Result        | Same type and values    |


In [79]:
a.__add__(5)

array([6, 3, 8])

In [80]:
a

array([ 1, -2,  3])

In [81]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
b.__add__(3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
a.__sub__(5)

array([-4, -7, -2])

In [85]:
c = a.__copy__()

In [86]:
c

array([ 1, -2,  3])

In [87]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a.__reduce__()

(<function numpy._core.multiarray._reconstruct>,
 (numpy.ndarray, (0,), b'b'),
 (1,
  (10,),
  dtype('int64'),
  False,
  b'\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00'))