# Generating random numbers

In [4]:
import numpy as np
rng = np.random.default_rng()
rng.random()

0.005590491828583288

In [5]:
rng.standard_normal(10)

array([ 0.81395523,  0.35300918, -0.98214848, -0.82137175,  1.24804616,
       -1.00318403,  1.13485384,  0.66926288,  0.49628594,  0.31620756])

In [11]:
rng.integers(low=0,high=10,size=5)

array([2, 8, 0, 3, 1])

In [12]:
import secrets

In [13]:
secrets.randbits(128)

209012968128244523675591289517988438766

# how to unique items and counts

In [14]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a))

[11 12 13 14 15 16 17 18 19 20]


In [15]:
np.unique(a,return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [19]:
unique_values,counts = np.unique(a,return_counts=True)
print(unique_values,counts)

[11 12 13 14 15 16 17 18 19 20] [3 2 2 2 1 1 1 1 1 1]


In [21]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
unique_rows = np.unique(a_2d,axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
unique_values,index,count = np.unique(a_2d,axis=0,return_counts=True,return_index=True)
unique_values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
count

array([2, 1, 1])

In [29]:
index

array([0, 1, 2])

# Trainsposing and reshaping a matrix

### this section covers 
        - arr.reshape()
        - arr.transpose()
        - arr.T

In [31]:
data = np.array([1,2,3,4,5,6,7,8])
data.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
data.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [39]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

### this section covers
        - np.flip()

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
rev_arr = np.flip(arr)
rev_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
arr_2d = np.arange(12).reshape(3,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
arr_2d_rev = np.flip(arr_2d)
arr_2d_rev

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

### reverse only columns

In [45]:
rev_col = np.flip(arr_2d, axis=1)
rev_col

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [47]:
arr_2d[1] = np.flip(arr_2d[1])
arr_2d

array([[ 0,  1,  2,  3],
       [ 7,  6,  5,  4],
       [ 8,  9, 10, 11]])

### you can also reverse the column at index position 1(the second column)

In [48]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
arr_2d

array([[ 0,  9,  2,  3],
       [ 7,  6,  5,  4],
       [ 8,  1, 10, 11]])