# Numpy fundamental

1. Array creation
2. indexing on ndarrays
3. i/o with numpy array
4. data types
5. broadcasting
6. copies and views
7. working with arrays of string and bytes
8. structured arrays
9. Universal functions basics

there are 6 machanisms for creating arrays
1. conversion from other python structure
2. intrinsic numpy array creation functions(arange,ones,zeros)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats6
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

In [1]:
import numpy as np
a1d = np.array([1,2,3,4,5])
a2d = np.array([[1,2],[3,4]])
a3d = np.array([[[1,2,3],[4,5,6]]])

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10,dtype = 'float')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## np.arange(start,end,step)

In [4]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. For example:

# 2d array creation function
### The 2D array creation functions e.g.
     - numpy.eye,
     - numpy.diag, and
     - numpy.vander
define properties of special matrices represented as 2D arrays.

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [8]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [9]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# general ndarray creation functions
### The ndarray creation functions e.g.
    - numpy.ones,
    - numpy.zeros, and
    - random
define arrays based upon the desired shape. The ndarray creation functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.

In [11]:
np.zeros((1,2))

array([[0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
from numpy.random import default_rng

In [16]:
default_rng(2).random((2,4))

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663]])

In [19]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

# Replicating, joining, or mutating existing arrays

In [20]:
arr = np.array([1,2,3,4,5,6])
b = arr[:2]
b+=1

In [22]:
print(arr,b)

[2 3 3 4 5 6] [2 3]
